[package]
name = "auther-lib"
description = "a password manager lib"

version = "1.2.0"
edition = "2021"

license = "MIT"

[dependencies]
rand_core = "0.6.4"
rand_hc = "0.3.1"
sha2 = "0.10.6"
toml = "0.7.2"